"""create users oauth accounts and characters

Revision ID: 24952763d13d
Revises:
Create Date: 2026-08-06 21:45:35.771048
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '24952763d13d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('avatar_url', sa.String(length=2048), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'characters',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('wallet', sa.Integer(), nullable=False),
        sa.Column('luck_current', sa.Integer(), nullable=False),
        sa.Column('luck_min', sa.Integer(), nullable=False),
        sa.Column('luck_max', sa.Integer(), nullable=False),
        sa.Column('int_current', sa.Integer(), nullable=False),
        sa.Column('int_min', sa.Integer(), nullable=False),
        sa.Column('int_max', sa.Integer(), nullable=False),
        sa.Column('ref_current', sa.Integer(), nullable=False),
        sa.Column('ref_min', sa.Integer(), nullable=False),
        sa.Column('ref_max', sa.Integer(), nullable=False),
        sa.Column('dex_current', sa.Integer(), nullable=False),
        sa.Column('dex_min', sa.Integer(), nullable=False),
        sa.Column('dex_max', sa.Integer(), nullable=False),
        sa.Column('cool_current', sa.Integer(), nullable=False),
        sa.Column('cool_min', sa.Integer(), nullable=False),
        sa.Column('cool_max', sa.Integer(), nullable=False),
        sa.Column('emp_current', sa.Integer(), nullable=False),
        sa.Column('emp_min', sa.Integer(), nullable=False),
        sa.Column('emp_max', sa.Integer(), nullable=False),
        sa.Column('will_current', sa.Integer(), nullable=False),
        sa.Column('will_min', sa.Integer(), nullable=False),
        sa.Column('will_max', sa.Integer(), nullable=False),
        sa.Column('tech_current', sa.Integer(), nullable=False),
        sa.Column('tech_min', sa.Integer(), nullable=False),
        sa.Column('tech_max', sa.Integer(), nullable=False),
        sa.Column('body_current', sa.Integer(), nullable=False),
        sa.Column('body_min', sa.Integer(), nullable=False),
        sa.Column('body_max', sa.Integer(), nullable=False),
        sa.Column('move_current', sa.Integer(), nullable=False),
        sa.Column('move_min', sa.Integer(), nullable=False),
        sa.Column('move_max', sa.Integer(), nullable=False),
        sa.Column('hp_current', sa.Integer(), nullable=False),
        sa.Column('hp_max', sa.Integer(), nullable=False),
        sa.Column('heavy_wounds_threshold', sa.Integer(), nullable=False),
        sa.Column('reputation', sa.Integer(), nullable=False),
        sa.Column('humanity', sa.Integer(), nullable=False),
        sa.Column('upgrade_points', sa.Integer(), nullable=False),
        sa.Column('armor_head', sa.Integer(), nullable=False),
        sa.Column('armor_head_penalty', sa.Integer(), nullable=False),
        sa.Column('armor_body', sa.Integer(), nullable=False),
        sa.Column('armor_body_penalty', sa.Integer(), nullable=False),
        sa.Column('armor_shield', sa.Integer(), nullable=False),
        sa.Column('armor_shield_penalty', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('0 <= armor_body', name='ck_armor_body_bounds'),
        sa.CheckConstraint('0 <= armor_body_penalty', name='ck_armor_body_penalty_bounds'),
        sa.CheckConstraint('0 <= armor_head', name='ck_armor_head_bounds'),
        sa.CheckConstraint('0 <= armor_head_penalty', name='ck_armor_head_penalty_bounds'),
        sa.CheckConstraint('0 <= armor_shield', name='ck_armor_shield_bounds'),
        sa.CheckConstraint('0 <= armor_shield_penalty', name='ck_armor_shield_penalty_bounds'),
        sa.CheckConstraint('0 <= hp_current AND hp_current <= hp_max', name='ck_hp_bounds'),
        sa.CheckConstraint('0 <= upgrade_points', name='ck_upgrade_points_bounds'),
        sa.CheckConstraint('body_min <= body_current AND body_current <= body_max', name='ck_body_bounds'),
        sa.CheckConstraint('cool_min <= cool_current AND cool_current <= cool_max', name='ck_cool_bounds'),
        sa.CheckConstraint('dex_min <= dex_current AND dex_current <= dex_max', name='ck_dex_bounds'),
        sa.CheckConstraint('emp_min <= emp_current AND emp_current <= emp_max', name='ck_emp_bounds'),
        sa.CheckConstraint('int_min <= int_current AND int_current <= int_max', name='ck_int_bounds'),
        sa.CheckConstraint('luck_min <= luck_current AND luck_current <= luck_max', name='ck_luck_bounds'),
        sa.CheckConstraint('move_min <= move_current AND move_current <= move_max', name='ck_move_bounds'),
        sa.CheckConstraint('ref_min <= ref_current AND ref_current <= ref_max', name='ck_ref_bounds'),
        sa.CheckConstraint('tech_min <= tech_current AND tech_current <= tech_max', name='ck_tech_bounds'),
        sa.CheckConstraint('will_min <= will_current AND will_current <= will_max', name='ck_will_bounds'),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'uq_characters_owner_id_title_lower', 'characters', ['owner_id', sa.literal_column('lower(title)')], unique=True
    )
    op.create_table(
        'oauth_accounts',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('provider', sa.String(length=32), nullable=False),
        sa.Column('provider_user_id', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_accounts_provider_identity'),
        sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_accounts_user_provider'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_accounts')
    op.drop_index('uq_characters_owner_id_title_lower', table_name='characters')
    op.drop_table('characters')
    op.drop_table('users')
    # ### end Alembic commands ###
